production:
  clients:
    default:
      database: kablammo
      hosts:
        - localhost:27017
development:
  clients:
    default:
      database: kablammo_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: kablammo_test
      hosts:
        - localhost:27017
